site_name: Packing-Box - Docker image for studying executable packing
repo_url: https://github.com/dhondta/docker-packing-box
site_author: dhondta
docs_dir: docs/pages
nav:
  - Introduction: index.md
  - 'Quick Start': quickstart.md
  - Usage:
    - Datasets: usage/datasets.md
    - Detectors: usage/detectors.md
    - Packers: usage/packers.md
    - Training: usage/training.md
    - Analysis: usage/analysis.md
  - Internals:
    - Executables: internals/executables.md
    - Datasets: internals/datasets.md
    - Items: internals/items.md
    - Detectors: internals/detectors.md
    - Packers: internals/packers.md
    - Unpackers: internals/unpackers.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
