site_name: Packing-Box - Docker image for studying executable packing
repo_url: https://github.com/dhondta/docker-packing-box
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: pages/index.md
  - 'Quick Start': pages/quickstart.md
  - Internals:
    - Executables: pages/internals/executables.md
    - Datasets: pages/internals/datasets.md
    - Items: pages/internals/items.md
    - Detectors: pages/internals/detectors.md
    - Packers: pages/internals/packers.md
    - Unpackers: pages/internals/unpackers.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
