site_name: "Packing-Box - Docker image for studying executable packing"
repo_url: https://github.com/dhondta/python-codext
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: index.md
  - Executables: executables.md
  - Datasets: datasets.md
  - Detectors: detectors.md
  - Packers: packers.md
  - Unpackers: unpackers.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
