site_name: "Packing-Box - Docker image for studying executable packing"
repo_url: https://github.com/dhondta/python-codext
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: pages/index.md
  - Executables: pages/executables.md
  - Datasets: pages/datasets.md
  - Detectors: pages/detectors.md
  - Packers: pages/packers.md
  - Unpackers: pages/unpackers.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
